# -------------------
# Banco de dados
# -------------------
spring.datasource.url=jdbc:mysql://localhost:3306/messengerdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=hawaiian11
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# -------------------
# JWT
# -------------------
# Chave secreta para assinar tokens JWT
JWT_SECRET_BASE64=SEU_SEGREDO_AQUI
